### ISSUE TITLE
Upgrade to cakePhp 3.0

### ISSUE THREAD

**Issue by gunnar-g** [Zuluru/Zuluru#12]

**Comment by Zuluru** [comment]
An upgrade to Cake 3 is largely finished, but in a private repository at the moment. The main outstanding piece is completing unit tests so that we can be confident that all the features are working as expected. If anyone is interested in assisting with this work, I'll be happy to get you set up with access.

**Comment by gunnar-g** [comment]
I'm not much of a php developer, but I can try. But as you know, time might
be an issue.  With the soccer season almost done, I should have a bit more
available.
Also, I was actually going to try the application, but cake 1.3 doesn't
really agree with php 7, so I couldn't get it run in the first place

2017-05-22 17:22 GMT+02:00 Zuluru <notifications@github.com>:

**Comment by aurelioaraujo** [comment]
Hi guys,we want to try out the Zuluru Application to manage the sports events of our University. However, the IT infrastructure (which will be responsible to host the application) does not agree to use a PHP bellow the version 7 (and the usage of a Docker container is not an option). How can we get access to the private repository that was updated over the cakephp 3.0?

**Comment by Zuluru** [comment]
Zuluru 3 is now in beta release on a number of sites that I manage. Among the incomplete pieces is any kind of installation routine, so getting it up and running is not quite straight-forward at the moment. It also hasn't been tested with PHP 7, though I don't expect any issues in that area.

Until the final release is ready (targeted for the end of May), have you checked out the demo site (demo.zuluru.org)? That will let you see all the functionality and perhaps get an idea of whether it's suitable for your needs.

**Comment by Zuluru** [comment]
The new version of Zuluru has finally been released! It's in a new repo, https://github.com/Zuluru/Zuluru3. Still hasn't been tested with PHP 7, would be interested to hear how that goes.
