### ISSUE TITLE
Team name doesn't use proper encoding

### ISSUE THREAD

**Issue by epalm** [Zuluru/Zuluru#14]
My team's name is "Rückspülung" but is being displayed as "RÃ¼ckspÃ¼lung" on the Dashboard page.

![2018-04-30 11_48_48-dashboard eric palmitesta _ toronto ultimate club - opera](https://user-images.githubusercontent.com/341068/39437123-edf8f4ee-4c6d-11e8-89ae-0717800aaa41.png)

Version appears to be "3.0.0beta"

**Comment by Zuluru** [comment]
The database structure has been migrated along for over 10 years now, so some columns were still defined as single-bytes, but holding multi-byte characters. The new version of the CakePHP framework (which Zuluru is built on) appears to be more rigorous in how they deal with these. I've updated the database, so this (and others) are appearing correctly again.

Can I ask whether the team name showed up correctly before in attendance emails? Also, please let me know whether this week's attendance emails have it correct.

**Comment by epalm** [comment]
Looks fine in the attendance email.

**Comment by Zuluru** [comment]
Great, thanks for the confirmation! Marking this as closed.
